# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b60d8aab11f3753cfdc4c73f436699fdfa2dd6de5fe1998409b90f6bb3b29a400016fae78e581618f8446e4ac5e31ef4edc0808a7d34c2a256c166779c109f

test:
  secret_key_base: ad7b0a2e2e91f4796f3b40145d775ff60c76ad47efe572cbbbac6da1b48678783bafde6e89f013e18360ca140c3c926930ae9ba9762af34cf5b0f4ae1ad6d9a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
